export const SETUP_FORM_FIELDS = {
  users: [
    { key: 'name', label: 'Full Name', required: true },
    { key: 'username', label: 'Username', required: true },
    { key: 'password', label: 'Password', type: 'password', requiredOnCreate: true },
    {
      key: 'type',
      label: 'Type',
      type: 'select',
      options: ['ADMIN', 'USER'],
      required: true,
    },
    {
      key: 'positionId',
      label: 'Position',
      type: 'select',
      optionSource: 'positions',
      optionValueKey: 'id',
      optionLabelKey: 'name',
    },
  ],
  companies: [
    { key: 'name', label: 'Company Name', required: true },
    { key: 'address', label: 'Address', required: true, className: 'sm:col-span-2' },
    { key: 'contactNo', label: 'Contact No.' },
    { key: 'tinNo', label: 'TIN' },
  ],
  branches: [
    {
      key: 'companyId',
      label: 'Company',
      type: 'select',
      optionSource: 'companies',
      optionValueKey: 'id',
      optionLabelKey: 'name',
      required: true,
    },
    { key: 'name', label: 'Branch Name', required: true },
  ],
  projects: [
    { key: 'name', label: 'Project Name', required: true },
    { key: 'address', label: 'Address', className: 'sm:col-span-2' },
  ],
  positions: [{ key: 'name', label: 'Position', required: true }],
  categories: [{ key: 'name', label: 'Category Name', required: true }],
  brands: [{ key: 'name', label: 'Brand Name', required: true }],
  models: [
    {
      key: 'brandId',
      label: 'Brand',
      type: 'select',
      optionSource: 'brands',
      optionValueKey: 'id',
      optionLabelKey: 'name',
      required: true,
    },
    { key: 'name', label: 'Model Name', required: true },
  ],
  units: [{ key: 'name', label: 'Unit Name', required: true }],
  items: [
    {
      key: 'brandId',
      label: 'Brand',
      type: 'select',
      optionSource: 'brands',
      optionValueKey: 'id',
      optionLabelKey: 'name',
      required: true,
    },
    {
      key: 'modelId',
      label: 'Model',
      type: 'select',
      optionSource: 'models',
      optionValueKey: 'id',
      optionLabelKey: 'name',
      required: true,
    },
    { key: 'name', label: 'Item Name', required: true, className: 'sm:col-span-2' },
    {
      key: 'unitId',
      label: 'Unit of Measure',
      type: 'select',
      optionSource: 'units',
      optionValueKey: 'id',
      optionLabelKey: 'name',
    },
  ],
  suppliers: [
    { key: 'name', label: 'Supplier Name', required: true },
    { key: 'address', label: 'Address', className: 'sm:col-span-2' },
    { key: 'tinNo', label: 'TIN' },
    { key: 'contact', label: 'Contact Person' },
    { key: 'phone', label: 'Contact No.' },
  ],
  customers: [
    { key: 'name', label: 'Customer Name', required: true },
    { key: 'address', label: 'Address', className: 'sm:col-span-2' },
    { key: 'tin', label: 'TIN' },
    { key: 'terms', label: 'Terms (days)', type: 'number' },
    {
      key: 'termsType',
      label: 'Terms Type',
      type: 'select',
      options: ['IN DAYS', 'NET'],
    },
  ],
}
